name: sudoku_utility
description: A Dart and Flutter library containing tools related to Sudoku puzzles. It involves generating, solving and handling puzzles.
version: 0.0.3
homepage: https://github.com/jagadish-chauhan/sudoku_utility

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  flutter_lints: ^1.0.0
  test: ^1.20.2